package org.apache.ddlutils.platform.postgresql;

/*
 * Copyright 1999-2006 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.IOException;

import org.apache.ddlutils.Platform;
import org.apache.ddlutils.alteration.RemoveColumnChange;
import org.apache.ddlutils.model.Column;
import org.apache.ddlutils.model.Database;
import org.apache.ddlutils.model.Table;

/**
 * SQL builder for PostgreSQL 14+ using {@code GENERATED BY DEFAULT AS IDENTITY} instead of explicit
 * {@code CREATE SEQUENCE} + {@code DEFAULT nextval(...)}.
 */
public class Postgre14SqlBuilder extends PostgreSqlBuilder
{
    /**
     * Creates a new builder instance.
     *
     * @param platform The platform this builder belongs to
     */
    public Postgre14SqlBuilder(Platform platform)
    {
        super(platform);
    }

    @Override
    protected void createAutoIncrementSequencesBeforeCreateTable(Table table)
    {
        // Identity columns own their sequence; no standalone CREATE SEQUENCE.
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected void writeColumnAutoIncrementStmt(Table table, Column column) throws IOException
    {
        print("GENERATED BY DEFAULT AS IDENTITY");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void dropTable(Table table) throws IOException
    {
        print("DROP TABLE ");
        printIdentifier(getTableName(table));
        print(" CASCADE");
        printEndOfStatement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getSelectLastIdentityValues(Table table)
    {
        Column[] columns = table.getAutoIncrementColumns();

        if (columns.length == 0)
        {
            return null;
        }
        else
        {
            StringBuffer result = new StringBuffer();

            result.append("SELECT ");
            for (int idx = 0; idx < columns.length; idx++)
            {
                if (idx > 0)
                {
                    result.append(", ");
                }
                result.append("currval(pg_get_serial_sequence(");
                result.append(escapePgStringLiteral(getTableName(table)));
                result.append(", ");
                result.append(escapePgStringLiteral(columns[idx].getName()));
                result.append(")) AS ");
                result.append(getDelimitedIdentifier(columns[idx].getName()));
            }
            return result.toString();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected void processChange(Database currentModel,
        Database desiredModel,
        RemoveColumnChange change) throws IOException
    {
        print("ALTER TABLE ");
        printlnIdentifier(getTableName(change.getChangedTable()));
        printIndent();
        print("DROP COLUMN ");
        printIdentifier(getColumnName(change.getColumn()));
        printEndOfStatement();
    }

    /**
     * Emits {@code ALTER TABLE ... ALTER COLUMN ... ADD GENERATED BY DEFAULT AS IDENTITY} for PostgreSQL 10+.
     * Use when migrating an existing column to identity without recreating the table.
     *
     * @param table  the table
     * @param column the target column definition (must be auto-increment in the desired model)
     */
    protected void writeAlterColumnAddGeneratedIdentity(Table table, Column column) throws IOException
    {
        print("ALTER TABLE ");
        printlnIdentifier(getTableName(table));
        printIndent();
        print("ALTER COLUMN ");
        printIdentifier(getColumnName(column));
        print(" ADD GENERATED BY DEFAULT AS IDENTITY");
        printEndOfStatement();
    }

    /**
     * Emits {@code ALTER TABLE ... ALTER COLUMN ... DROP IDENTITY IF EXISTS}.
     *
     * @param table  the table
     * @param column the column to strip identity from
     */
    protected void writeAlterColumnDropIdentity(Table table, Column column) throws IOException
    {
        print("ALTER TABLE ");
        printlnIdentifier(getTableName(table));
        printIndent();
        print("ALTER COLUMN ");
        printIdentifier(getColumnName(column));
        print(" DROP IDENTITY IF EXISTS");
        printEndOfStatement();
    }

    /**
     * Aligns the identity sequence with the current maximum column value (same intent as Oracle
     * {@code CREATE SEQUENCE ... START WITH max+1}). Safe on empty tables ({@code MAX} is null).
     *
     * @param table  the table
     * @param column the identity column
     */
    protected void writeSetvalIdentityFromMax(Table table, Column column) throws IOException
    {
        print("SELECT setval(pg_get_serial_sequence(");
        print(escapePgStringLiteral(getTableName(table)));
        print(", ");
        print(escapePgStringLiteral(column.getName()));
        print("), (SELECT COALESCE(MAX(");
        printIdentifier(getColumnName(column));
        print("), 0) FROM ");
        printIdentifier(getTableName(table));
        print("), true)");
        printEndOfStatement();
    }

    protected static String escapePgStringLiteral(String value)
    {
        if (value == null)
        {
            return "''";
        }
        return "'" + value.replace("'", "''") + "'";
    }
}
